### PR TITLE
https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-790

### PR DESCRIPTION
**Pull request by stiemannkj1**
Fixed hidden client state for render="@all" and Ajax navigation (which performs
an implicit render="@all") use cases.

### CODE REVIEW

**Comment by stiemannkj1** [comment]
cc @BalusC, @ngriffin7a

**Comment by stiemannkj1** [comment]
See this comment on 790 for more details: https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-790?focusedCommentId=393702&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-393702

**Comment by stiemannkj1** [comment]
Closing this PR since an alternative fix was made by @BalusC here: https://github.com/jsf-spec/mojarra/commit/41a60c0d6bb0af295ee271180b8bac4d550cffee

**Comment by BalusC** [comment]
Thanks for the refactoring hints tho.

I noticed that you mixed `namingContainerId` and `namingContainerPrefix` variable names. The former represents the `UIViewRoot#getContainerClientId()` and the latter represents the same value but then suffixed with the separator character.

**Pull request closed without merging**
